version: '3.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: MongoDB
    hostname: MongoDB
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    hostname: mongo-express
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
